<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11252" started-at="2014-08-29T08:08:12Z" finished-at="2014-08-29T08:08:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11252" started-at="2014-08-29T08:08:12Z" finished-at="2014-08-29T08:08:24Z">
      <class name="com.example.tests.ContactCreationTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.ContactCreationTest@c38a936]" name="setUp" is-config="true" duration-ms="6300" started-at="2014-08-29T11:08:12Z" finished-at="2014-08-29T11:08:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testNonEmptyContactCreation(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTest@c38a936]" name="testNonEmptyContactCreation" duration-ms="2670" started-at="2014-08-29T11:08:19Z" data-provider="randomValidContactGenerator" finished-at="2014-08-29T11:08:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstName=testName193167332vzygmvfkamkzicpvkruu, lastName=]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ContactData [firstName=Mazgalin, lastName=Dmitry] != ContactData [firstName=, lastName=testName193167332vzygmvfkamkzicpvkruu] expected [ContactData [firstName=Mazgalin, lastName=Dmitry]] but found [ContactData [firstName=, lastName=testName193167332vzygmvfkamkzicpvkruu]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [firstName=Mazgalin, lastName=Dmitry] != ContactData [firstName=, lastName=testName193167332vzygmvfkamkzicpvkruu] expected [ContactData [firstName=Mazgalin, lastName=Dmitry]] but found [ContactData [firstName=, lastName=testName193167332vzygmvfkamkzicpvkruu]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTest.testNonEmptyContactCreation(ContactCreationTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNonEmptyContactCreation -->
        <test-method status="FAIL" signature="testNonEmptyContactCreation(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactCreationTest@c38a936]" name="testNonEmptyContactCreation" duration-ms="2156" started-at="2014-08-29T11:08:21Z" data-provider="randomValidContactGenerator" finished-at="2014-08-29T11:08:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstName=testName-603993505zosabxrlcdntrvpenqpy, lastName=testName227590103ncdjyeoitekotuxisesa]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [4]: ContactData [firstName=testName-603993505zosabxrlcdntrvpenqpy, lastName=testName227590103ncdjyeoitekotuxisesa] != ContactData [firstName=testName1499581609jzvmoqwspjaviveieakc, lastName=testName-161900555swrybptqhpertmejouxt] expected [ContactData [firstName=testName-603993505zosabxrlcdntrvpenqpy, lastName=testName227590103ncdjyeoitekotuxisesa]] but found [ContactData [firstName=testName1499581609jzvmoqwspjaviveieakc, lastName=testName-161900555swrybptqhpertmejouxt]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [4]: ContactData [firstName=testName-603993505zosabxrlcdntrvpenqpy, lastName=testName227590103ncdjyeoitekotuxisesa] != ContactData [firstName=testName1499581609jzvmoqwspjaviveieakc, lastName=testName-161900555swrybptqhpertmejouxt] expected [ContactData [firstName=testName-603993505zosabxrlcdntrvpenqpy, lastName=testName227590103ncdjyeoitekotuxisesa]] but found [ContactData [firstName=testName1499581609jzvmoqwspjaviveieakc, lastName=testName-161900555swrybptqhpertmejouxt]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:549)
	at org.testng.Assert.assertEquals(Assert.java:514)
	at com.example.tests.ContactCreationTest.testNonEmptyContactCreation(ContactCreationTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNonEmptyContactCreation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.ContactCreationTest@c38a936]" name="tearDown" is-config="true" duration-ms="104" started-at="2014-08-29T11:08:24Z" finished-at="2014-08-29T11:08:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.ContactCreationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
